// Chemfiles, a modern library for chemistry file reading and writing
// Copyright (C) Guillaume Fraux and contributors -- BSD license

#include <string_view>
#include <vector>

#include "chemfiles/error_fmt.hpp"
#include "chemfiles/parse.hpp"
#include "chemfiles/types.hpp"
#include "chemfiles/utils.hpp"

#include "chemfiles/Atom.hpp"
#include "chemfiles/File.hpp"
#include "chemfiles/Format.hpp"
#include "chemfiles/FormatMetadata.hpp"
#include "chemfiles/Frame.hpp"
#include "chemfiles/UnitCell.hpp"

#include "chemfiles/formats/_CON.hpp"

using namespace chemfiles;

template <> const FormatMetadata &chemfiles::format_metadata<ConFormat>() {
    static FormatMetadata metadata;
    metadata.name = "Con";
    metadata.extension = ".con";
    metadata.description = "Con file format";
    metadata.reference = "";

    metadata.read = true;
    metadata.write = true;
    metadata.memory = true;

    metadata.positions = true;
    metadata.velocities = false;
    metadata.unit_cell = true;
    metadata.atoms = true;
    metadata.bonds = false;
    metadata.residues = false;
    return metadata;
}

void ConFormat::read_next(Frame &frame) {
    // 1. Prebox Header (2 lines)
    file_.readline();
    file_.readline();

    // 2. Box Lengths (Line 3)
    // Use idiomatic 'scan' which handles tabs/spaces automatically and
    // zero-copy
    double a = 0;
    double b = 0;
    double c = 0;
    scan(file_.readline(), a, b, c);

    // 3. Angles (Line 4)
    double alpha = 0;
    double beta = 0;
    double gamma = 0;
    scan(file_.readline(), alpha, beta, gamma);

    frame.set_cell(UnitCell({a, b, c}, {alpha, beta, gamma}));

    // 4. Postbox Header (2 lines)
    file_.readline();
    file_.readline();

    // 5. Number of atom types (Line 7)
    size_t natm_types = parse<size_t>(file_.readline());

    // 6. Atoms per type (Line 8) - Variable length, use helper
    auto natms_per_type = parse_vector<size_t>(file_.readline(), natm_types);

    // 7. Masses per type (Line 9) - Variable length, use helper
    auto masses_per_type = parse_vector<double>(file_.readline(), natm_types);

    // Calculate total atoms
    size_t total_atoms = 0;
    for (auto n : natms_per_type)
        total_atoms += n;
    frame.reserve(total_atoms);

    // 8. Atom Data
    for (size_t i = 0; i < natm_types; ++i) {
        auto symbol = std::string(trim(file_.readline()));
        file_.readline(); // Skip "Coordinates of Component X"

        double mass = masses_per_type[i];
        size_t num_atoms = natms_per_type[i];

        for (size_t j = 0; j < num_atoms; ++j) {
            auto line = file_.readline();
            double x = 0;
            double y = 0;
            double z = 0;
            double atom_id_val = 0;
            double is_fixed_val = 0;

            // scan automatically handles whitespace splitting
            scan(line, x, y, z, is_fixed_val, atom_id_val);

            Atom atom(symbol);
            atom.set_mass(mass);
            atom.set("is_fixed", is_fixed_val != 0.0);
            atom.set("atom_id", atom_id_val);

            frame.add_atom(std::move(atom), Vector3D(x, y, z));
        }
    }
}

void ConFormat::write_next(const Frame &frame) {
    // The Con format requires atoms to be grouped by type (blocks).
    // We need to group chemfiles atoms by their name to match this structure.

    // Structure to hold data for one component type
    struct ComponentBlock {
        std::string symbol;
        double mass;
        std::vector<size_t> atom_indices;
    };

    std::vector<ComponentBlock> components;
    // Map symbol to index in `components` vector
    std::map<std::string, size_t> type_map;

    const auto &positions = frame.positions();

    for (size_t i = 0; i < frame.size(); ++i) {
        const auto &atom = frame[i];
        std::string name = atom.name();
        if (name.empty())
            name = "X";

        if (type_map.find(name) == type_map.end()) {
            type_map[name] = components.size();
            ComponentBlock block;
            block.symbol = name;
            block.mass = atom.mass();
            components.push_back(block);
        }

        components[type_map[name]].atom_indices.push_back(i);
    }

    // --- Header ---
    // Lines 1-2: Prebox
    file_.print("Generated by chemfiles\n");
    file_.print("Prebox Header Line 2\n");

    // Line 3: Box Lengths
    auto cell = frame.cell();
    auto lengths = cell.lengths();
    file_.print("{:g} {:g} {:g}\n", lengths[0], lengths[1], lengths[2]);

    // Line 4: Angles
    auto angles = cell.angles();
    file_.print("{:g} {:g} {:g}\n", angles[0], angles[1], angles[2]);

    // Lines 5-6: Postbox
    file_.print("Postbox Header Line 1\n");
    file_.print("Postbox Header Line 2\n");

    // Line 7: Num types
    file_.print("{}\n", components.size());

    // Line 8: Atoms per type
    for (size_t i = 0; i < components.size(); ++i) {
        file_.print("{}", components[i].atom_indices.size());
        if (i < components.size() - 1)
            file_.print(" ");
    }
    file_.print("\n");

    // Line 9: Masses per type
    for (size_t i = 0; i < components.size(); ++i) {
        file_.print("{:g}", components[i].mass);
        if (i < components.size() - 1)
            file_.print(" ");
    }
    file_.print("\n");

    // --- Atom Blocks ---
    for (size_t i = 0; i < components.size(); ++i) {
        const auto &comp = components[i];

        file_.print("{}\n", comp.symbol);
        file_.print("Coordinates of Component {}\n", i + 1);

        for (size_t atom_idx : comp.atom_indices) {
            const auto &atom = frame[atom_idx];
            const auto &pos = positions[atom_idx];

            // Extract preserved properties or defaults
            double is_fixed_val = 0.0;
            auto fixed_prop = atom.get("is_fixed");
            if (fixed_prop && fixed_prop->kind() == Property::BOOL &&
                fixed_prop->as_bool()) {
                is_fixed_val = 1.0;
            }

            double atom_id_val = static_cast<double>(atom_idx);
            auto id_prop = atom.get("atom_id");
            if (id_prop && id_prop->kind() == Property::DOUBLE) {
                atom_id_val = id_prop->as_double();
            }

            file_.print("{:.17g} {:.17g} {:.17g} {:.0f} {:.0f}\n", pos[0],
                        pos[1], pos[2], is_fixed_val, atom_id_val);
        }
    }
}

optional<uint64_t> ConFormat::forward() {
    auto position = file_.tellpos();

    // Try reading Line 1
    auto line = file_.readline();
    if (trim(line).empty() || file_.eof()) {
        return nullopt;
    }

    try {
        // Skip 5 lines (Header + Box + Postbox)
        for (int i = 0; i < 5; ++i)
            file_.readline();

        // Num Types
        size_t natm_types = parse<size_t>(file_.readline());

        // Atoms per type (Variable length line)
        auto counts_line = file_.readline();
        size_t total_atoms = 0;

        // Manual loop for efficiency (avoid allocations)
        size_t start = counts_line.find_first_not_of(WHITESPACE);
        while (start != std::string_view::npos) {
            size_t end = counts_line.find_first_of(WHITESPACE, start);
            auto token = counts_line.substr(start, end - start);
            total_atoms += parse<size_t>(token);

            if (end == std::string_view::npos)
                break;
            start = counts_line.find_first_not_of(WHITESPACE, end);
        }

        file_.readline(); // Skip masses

        // Skip atom blocks
        size_t lines_to_skip = (2 * natm_types) + total_atoms;
        for (size_t i = 0; i < lines_to_skip; ++i) {
            file_.readline();
            if (file_.eof()) {
                throw format_error(
                    "con format: unexpected EOF while forwarding");
            }
        }

    } catch (const Error &e) {
        throw format_error("con format: error while forwarding: {}", e.what());
    }

    return position;
}
