include(CheckCXXCompilerFlag)

# C++11 support.
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
elseif(COMPILER_SUPPORTS_CXXOX)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x")
else()
    if(MSVC)
        if(MSVC_VERSION LESS 1900)
            message(SEND_ERROR "MSVC < 14.0 is not supported. Please update your compiler or use mingw")
        endif()
    else()
        message(SEND_ERROR "The ${CMAKE_CXX_COMPILER} compiler lacks C++11 support. Use another compiler.")
    endif()
endif()

macro(set_debug_flag_if_possible _flag_)
    CHECK_CXX_COMPILER_FLAG("${_flag_}" CXX_SUPPORTS${_flag_})
    if(CXX_SUPPORTS${_flag_})
        set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${_flag_}")
    endif()
endmacro()

# Add some warnings in debug mode
if(MSVC)
    # set_debug_flag_if_possible("/W4")
else()
    set_debug_flag_if_possible("-Wall")
    set_debug_flag_if_possible("-Wextra")
    set_debug_flag_if_possible("-Wconversion")
    set_debug_flag_if_possible("-Wsign-conversion")
    set_debug_flag_if_possible("-Wsign-promo")
    set_debug_flag_if_possible("-Wsuggest-override")
    set_debug_flag_if_possible("-pedantic")
endif()

include(CheckCCompilerFlag)
CHECK_C_COMPILER_FLAG("-std=c99" CC_SUPPORTS_C99)

if(CC_SUPPORTS_C99)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99")
endif()

if(MSVC)
    add_definitions("/D COMPILER_IS_MSVC")
    add_definitions("/D NOMINMAX")
endif()
